blu3print:
  max-scale: 8 # Maximum scale of a Blu3Print
  cooldown: 1500 # Cooldown in ms between two Blu3print usages
  recipe: # Recipe for crafting a Blu3Print
    ingredients:
      - PAPER
      - LAPIS_LAZULI
      - FEATHER